package com.hyphenate.easeui.model;

import com.hyhenate.easeui.R;
import com.hyphenate.easeui.domain.EaseEmojicon;
import com.hyphenate.easeui.domain.EaseEmojicon.Type;
import com.hyphenate.easeui.utils.EaseSmileUtils;

public class EaseDefaultEmojiconDatas {
    
    private static String[] emojis = new String[]{
        EaseSmileUtils.ee_1,
        EaseSmileUtils.ee_2,
        EaseSmileUtils.ee_3,
        EaseSmileUtils.ee_4,
        EaseSmileUtils.ee_5,
        EaseSmileUtils.ee_6,
        EaseSmileUtils.ee_7,
        EaseSmileUtils.ee_8,
        EaseSmileUtils.ee_9,
        EaseSmileUtils.ee_10,
        EaseSmileUtils.ee_11,
        EaseSmileUtils.ee_12,
        EaseSmileUtils.ee_13,
        EaseSmileUtils.ee_14,
        EaseSmileUtils.ee_15,
        EaseSmileUtils.ee_16,
        EaseSmileUtils.ee_17,
        EaseSmileUtils.ee_18,
        EaseSmileUtils.ee_19,
        EaseSmileUtils.ee_20,
        EaseSmileUtils.ee_21,
        EaseSmileUtils.ee_22,
        EaseSmileUtils.ee_23,
        EaseSmileUtils.ee_24,
        EaseSmileUtils.ee_25,
        EaseSmileUtils.ee_26,
        EaseSmileUtils.ee_27,
        EaseSmileUtils.ee_28,
        EaseSmileUtils.ee_29,
        EaseSmileUtils.ee_30,
        EaseSmileUtils.ee_31,
        EaseSmileUtils.ee_32,
        EaseSmileUtils.ee_33,
        EaseSmileUtils.ee_34,
        EaseSmileUtils.ee_35,
        EaseSmileUtils.ee_36,
        EaseSmileUtils.ee_37,
        EaseSmileUtils.ee_38,
        EaseSmileUtils.ee_39,
        EaseSmileUtils.ee_40,
        EaseSmileUtils.ee_41,
        EaseSmileUtils.ee_42,
        EaseSmileUtils.ee_43,
        EaseSmileUtils.ee_44,
        EaseSmileUtils.ee_45,
        EaseSmileUtils.ee_46,
        EaseSmileUtils.ee_47,
        EaseSmileUtils.ee_48,
        EaseSmileUtils.ee_49,
        EaseSmileUtils.ee_50,
        EaseSmileUtils.ee_51,
        EaseSmileUtils.ee_52,
        EaseSmileUtils.ee_53,
        EaseSmileUtils.ee_54,
        EaseSmileUtils.ee_55,
        EaseSmileUtils.ee_56,
        EaseSmileUtils.ee_57,
        EaseSmileUtils.ee_58,
        EaseSmileUtils.ee_59,
        EaseSmileUtils.ee_60,
        EaseSmileUtils.ee_61,
        EaseSmileUtils.ee_62,
        EaseSmileUtils.ee_63,
        EaseSmileUtils.ee_64,
        EaseSmileUtils.ee_65,
        EaseSmileUtils.ee_66,
        EaseSmileUtils.ee_67,
        EaseSmileUtils.ee_68,
        EaseSmileUtils.ee_69,
        EaseSmileUtils.ee_70,
        EaseSmileUtils.ee_71,
        EaseSmileUtils.ee_72,
        EaseSmileUtils.ee_73,
        EaseSmileUtils.ee_74,
        EaseSmileUtils.ee_75,
        EaseSmileUtils.ee_76,
        EaseSmileUtils.ee_77,
        EaseSmileUtils.ee_78,
        EaseSmileUtils.ee_79,
        EaseSmileUtils.ee_80,
        EaseSmileUtils.ee_81,
        EaseSmileUtils.ee_82,
        EaseSmileUtils.ee_83,
        EaseSmileUtils.ee_84,
        EaseSmileUtils.ee_85,
        EaseSmileUtils.ee_86,
        EaseSmileUtils.ee_87,
        EaseSmileUtils.ee_88,
        EaseSmileUtils.ee_89,
        EaseSmileUtils.ee_90,



    };
    
    private static int[] icons = new int[]{
        R.drawable.ee_1,
        R.drawable.ee_2,
        R.drawable.ee_3,
        R.drawable.ee_4,
        R.drawable.ee_5,
        R.drawable.ee_6,
        R.drawable.ee_7,
        R.drawable.ee_8,
        R.drawable.ee_9,
        R.drawable.ee_10,
        R.drawable.ee_11,
        R.drawable.ee_12,
        R.drawable.ee_13,
        R.drawable.ee_14,
        R.drawable.ee_15,
        R.drawable.ee_16,
        R.drawable.ee_17,
        R.drawable.ee_18,
        R.drawable.ee_19,
        R.drawable.ee_20,
        R.drawable.ee_21,
        R.drawable.ee_22,
        R.drawable.ee_23,
        R.drawable.ee_24,
        R.drawable.ee_25,
        R.drawable.ee_26,
        R.drawable.ee_27,
        R.drawable.ee_28,
        R.drawable.ee_29,
        R.drawable.ee_30,
        R.drawable.ee_31,
        R.drawable.ee_32,
        R.drawable.ee_33,
        R.drawable.ee_34,
        R.drawable.ee_35,
        R.drawable.ee_36,
        R.drawable.ee_37,
        R.drawable.ee_38,
        R.drawable.ee_39,
        R.drawable.ee_40,
        R.drawable.ee_41,
        R.drawable.ee_42,
        R.drawable.ee_43,
        R.drawable.ee_44,
        R.drawable.ee_45,
        R.drawable.ee_46,
        R.drawable.ee_47,
        R.drawable.ee_48,
        R.drawable.ee_49,
        R.drawable.ee_50,
        R.drawable.ee_51,
        R.drawable.ee_52,
        R.drawable.ee_53,
        R.drawable.ee_54,
        R.drawable.ee_55,
        R.drawable.ee_56,
        R.drawable.ee_57,
        R.drawable.ee_58,
        R.drawable.ee_59,
        R.drawable.ee_60,
        R.drawable.ee_61,
        R.drawable.ee_62,
        R.drawable.ee_63,
        R.drawable.ee_64,
        R.drawable.ee_65,
        R.drawable.ee_66,
        R.drawable.ee_67,
        R.drawable.ee_68,
        R.drawable.ee_69,
        R.drawable.ee_70,
        R.drawable.ee_71,
        R.drawable.ee_72,
        R.drawable.ee_73,
        R.drawable.ee_74,
        R.drawable.ee_75,
        R.drawable.ee_76,
        R.drawable.ee_77,
        R.drawable.ee_78,
        R.drawable.ee_79,
        R.drawable.ee_80,
        R.drawable.ee_81,
        R.drawable.ee_82,
        R.drawable.ee_83,
        R.drawable.ee_84,
        R.drawable.ee_85,
        R.drawable.ee_86,
        R.drawable.ee_87,
        R.drawable.ee_88,
        R.drawable.ee_89,
        R.drawable.ee_90,
    };
    
    
    private static final EaseEmojicon[] DATA = createData();
    
    private static EaseEmojicon[] createData(){
        EaseEmojicon[] datas = new EaseEmojicon[icons.length];
        for(int i = 0; i < icons.length; i++){
            datas[i] = new EaseEmojicon(icons[i], emojis[i], Type.NORMAL);
        }
        return datas;
    }
    
    public static EaseEmojicon[] getData(){
        return DATA;
    }
}
